all: myls mysearch mystat mytail

myls: myls.c
	gcc -Wall -o myls myls.c

mystat: mystat.c
	gcc -Wall -o mystat mystat.c

mysearch: mysearch.c
	gcc -Wall -o mysearch mysearch.c

mytail: mytail.c
	gcc -Wall -o mytail mytail.c