all: myls mysearch mystat mytail

myls: myls-melo.c
	gcc -Wall -o myls myls-melo.c

mystat: mystat-melo.c
	gcc -Wall -o mystat mystat-melo.c

mysearch: mysearch-melo.c
	gcc -Wall -o mysearch mysearch-melo.c

mytail: mytail-melo.c
	gcc -Wall -o mytail mytail-melo.c